### PR TITLE
Pr 20200619 new exhale limits new ki schedule data

### PR DESCRIPTION
**Pull request by inceptionev**
Further tuning of the AIR control values trades some exhale fall time performance for better overshoot characteristics.

Stablity in test 5, 7, and 8 is improved, but 5 still possibly an issue.  Problematic undershoot in Test 6 is reduced.

### CODE REVIEW

**Comment by jlebar** [comment]
Edwin, would it help if I wrote you a script to do a parameter sweep?

It's a little tricky because you have to manually adjust the test lung during the test.  :-/

**Comment by inceptionev** [comment]
I'm interested!  Tell me more what you are thinking?Are we talking like a version of run_covent_tests.py that would run a number of different control gains at each set of parameters?

**Comment by jlebar** [comment]
> Are we talking like a version of run_covent_tests.py that would run a number of different control gains at each set of parameters?

Yeah, something like that.  I dunno if I can do it within the time that we have in a way that would be useful to you, though.  Also the thing about parameter sweeps is that they take a long time unless you can be intelligent about how you choose the parameters, and that also seems hard.

But if you have something concrete I can try.

**Comment by jlebar** [comment]
Will merge once pre-commits pass.

**Pull request merged**
