### PR TITLE
[GUI] Remove FPS counter and make window fullscreen on release builds

### PR DESCRIPTION
**Pull request by paulovap**

### CODE REVIEW

**Comment by paulovap** [comment]
> Can we write down somewhere how to control whether it's a debug build?

@jlebar you mean `qmake "CONFIG+=release"` ? Where should we put this information?

**Comment by jlebar** [comment]
> @jlebar you mean qmake "CONFIG+=release" ?

Yeah, guess so.

> Where should we put this information?

Maybe a line in https://github.com/RespiraWorks/VentilatorSoftware/wiki/GUI-Deployment-Strategy ?

**Comment by paulovap** [comment]
> > @jlebar you mean qmake "CONFIG+=release" ?
> 
> Yeah, guess so.
> 
> > Where should we put this information?
> 
> Maybe a line in https://github.com/RespiraWorks/VentilatorSoftware/wiki/GUI-Deployment-Strategy ?

How about `gui.sh --build --release`? or `gui.sh --build` release by default.

**Comment by jlebar** [comment]
> How about gui.sh --build --release? or gui.sh --build release by default.

either sounds good to me.

**Pull request merged**
