### PR TITLE
Slankard/pulseaudio tweaks

### PR DESCRIPTION
**Pull request by twslankard**
Add pulseaudio service config files (oops, forgot them).
    Fix auto-login issue by providing our own lightdm.conf file with autologin-user=pi.
    Update password from raspberry to respiraworks.
    Add a tag in the ansible playbook to skip the very slow Docker steps.

### CODE REVIEW

**Comment by martukas** [comment]
I'm also satisfied in principle. Is there any way I can confiirm that it does what it claims to do? A test I can perform manually or an artifact I can see that it produced?

**Comment by twslankard** [comment]
There are a few ways to verify this. One is to follow the instructions in the "GUI Deployment Strategy" page, effectively creating an RPi image and either running it in a VM or on a device. I'm trying both at the moment.

**Comment by martukas** [comment]
Ok, I will standby for word of your verification.

**Comment by twslankard** [comment]
Okay things seem to work as intended, waiting for circleci checks.

**Pull request merged**
