### PR TITLE
Cache latest gui docker image & spin up on boot

### PR DESCRIPTION
**Pull request by a-vinod**
Added steps to cache the latest respiraworks/gui docker image from docker hub into the raspbian image and spin it up on boot.

### CODE REVIEW

**Comment by jkff** [comment]
Drive-by comment: I don't think we should be auto-updating the GUI, or have it have any network connectivity at all in a production setting. For reasons, see https://github.com/RespiraWorks/VentilatorSoftware/issues/163#issuecomment-625008709

**Comment by a-vinod** [comment]
Looks like I missed that discussion. I'll cut out the auto updating code for now so only the latest gui image is cached upon raspbian image creation. 

Let's get some ideas on if and how our update deploying strategy is in the next software meeting as Hugh mentioned.

**Comment by twslankard** [comment]
@jkff @a-vinod 

I believe this only updates the image that is getting cached in the RPi image that the playbook produces. (Correct me if I'm wrong, Arjun.)

**Comment by a-vinod** [comment]
Correct! Updated the title and description to be a bit more clear.

**Pull request merged**
