### PR TITLE
Delete unused .ino files.

### PR DESCRIPTION
**Pull request by jlebar**
These were renamed to .cpp in 6d3760b123bb8384f86497b7e55c9ce83e34edc5.
<pr-train-toc>

#### PR chain:
👉 #86 (Delete unused .ino files.) 👈 **YOU ARE HERE**

</pr-train-toc>

### CODE REVIEW

**Comment by khuey** [comment]
lgtm.

**Comment by verityRF** [comment]
Nothing is lost by doing this, everything's in those .cpp files. Good to go!

**Comment by jlebar** [comment]
Thank you for the reviews!

**Comment by jlebar** [comment]
Ugh, this merged into the wrong branch.  pr-train fail.  :(

**Pull request merged**
