### PR TITLE
Bitfield-ify UART `request` field.

### PR DESCRIPTION
**Pull request by jlebar**
<git-pr-chain>

#### Commits in this PR
1. Bitfield-ify UART `request` field.

#### [PR chain](https://github.com/jlebar/git-pr-chain)
1. 👉 #340 Bitfield-ify UART `request` field. 👈 **YOU ARE HERE**
1. #348 Bitfield-ify UART status register.
1. #342 Bitfield-ify UART intClear register.
1. #343 C++ nits in uart_dma.
1. #344 Templatize CircularBuffer's datatype.

</git-pr-chain>

### CODE REVIEW

**Comment by Miceuz** [comment]
Note that this changes register access to read-modify-write against which @sglow was advising. Formally all the bits in the register is marked write only.

**Comment by jlebar** [comment]
> Formally all the bits in the register is marked write only.

That was why I thought it was safe.  My understanding is that when we read them, they are always 0 -- is that correct?

**Comment by Miceuz** [comment]
Yeah, I have double checked the documentation:

> Software can only write to this bit. Reading this bit returns the reset value.

Reset value being 0. So yeah, I reckon it's safe!

**Comment by sglow** [comment]
For what it's worth, I'm warming up to the idea of using bit-fields on registers.  When I first saw it it struck me as blasphemy, but there's no question that the code is easier to read.

We'll have to be careful since it can't be done on all registers, but I suppose one has to be careful when messing around at the hardware level anyway, so this don't really change things too much.

**Pull request merged**
