### PR TITLE
Fix typo in sensor readings.

### PR DESCRIPTION
**Pull request by jlebar**
<git-pr-chain>

#### Commits in this PR
1. Fix typo in sensor readings.
    
    We were reading the wrong sensor for outflow delta.
    
    This was not caught by code review because it was introduced in a "fix
    review comments" change.  It was not caught by a unit test because unit
    tests always feed the same inflow and outflow data.

#### [PR chain](https://github.com/jlebar/git-pr-chain)
1. #294 Update badges in README.md.
1. 👉 #303 Fix typo in sensor readings. 👈 **YOU ARE HERE**
1. #293 Fix trailing whitespace in a README.md file.

</git-pr-chain>

### CODE REVIEW

**Comment by jlebar** [comment]
This definitely needs a test, but since I am the only one with a working board right now, I am blocking others, so I hope it's OK if I leave this test to someone else.

**Comment by jlebar** [comment]
Credit to @sglow for finding this.

**Comment by jkff** [comment]
I'm surprised that sensors_test didn't catch this though... I'll look into it later today.

**Comment by jlebar** [comment]
> I'm surprised that sensors_test didn't catch this though...

See commit message :)

**Comment by jlebar** [comment]
Fixed in f46b70dc2439360d096bf149f31143779bf25393

**Pull request closed without merging**
