### PR TITLE
Issue #92 : Update LICENSE

### LINKED ISSUE #92: update license to apache v2

### PR DESCRIPTION
**Pull request by neelfirst**
Per https://respiraworks.slack.com/archives/C0100SF3N5T/p1586663955377400

Updating license from GPLv3 to Apache v2.

Closes #92

### CODE REVIEW

**Comment by jlebar** [comment]
Sadly, it's more complicated than just changing the file.

Everyone who has copyright over any code in the repository has to consent to the license change.

**Comment by jlebar** [comment]
We'll also want to change or remove the license headers on the files, which currently say GPLv3.

**Comment by neelfirst** [comment]
Not sure if I can just strike out the QT headers, which say GPLv3 or pay up.

**Comment by jlebar** [comment]
> Not sure if I can just strike out the QT headers, which say GPLv3 or pay up.

Yes, that needs to stay!

(FTR Qt is licensed as GPL 2.0, GPL 3.0, or LGPL 3.0.  The last one is the critical piece; if it were only available under plain GPL, we wouldn't be able to use it without licensing the whole GUI app as GPL.)

**Comment by jlebar** [comment]
LMK if/when you'd like a review; I stand ready.  :)

Note that there are GPL license headers at the top of most of the source files; these should be replaced or simply removed.  Doesn't have to be in this PR, and I can help write a script to do that if it's annoying.

**Comment by neelfirst** [comment]
I only see four files (all in /gui) as having GPL headers...

```
neel@neel-surface:~/VentilatorSoftware$ grep -Hrni gpl
.git/COMMIT_EDITMSG:1:removed GPLv3 license from controller subfolder
.git/logs/HEAD:4:92521b81cc23a46ef946df465aa4db150f796285 6ef364b2ec27363547146d37f9d5ab28c5c855b1 neelfirst <neelfirst@gmail.com> 1586969115 -0700     commit: removed GPLv3 license from controller subfolder
.git/logs/refs/heads/issue-92_license-update:3:92521b81cc23a46ef946df465aa4db150f796285 6ef364b2ec27363547146d37f9d5ab28c5c855b1 neelfirst <neelfirst@gmail.com> 1586969115 -0700       commit: removed GPLv3 license from controller subfolder
Binary file .git/objects/pack/pack-97e9f370d3168f8999c242c4405618f3b1ec7a7a.pack matches
gui/ControlPanel.qml:8:** $QT_BEGIN_LICENSE:GPL$
gui/ControlPanel.qml:21:** the Free Software Foundation and appearing in the file LICENSE.GPL3
gui/ControlPanel.qml:24:** be met: https://www.gnu.org/licenses/gpl-3.0.html.
gui/ScopeView.qml:8:** $QT_BEGIN_LICENSE:GPL$
gui/ScopeView.qml:21:** the Free Software Foundation and appearing in the file LICENSE.GPL3
gui/ScopeView.qml:24:** be met: https://www.gnu.org/licenses/gpl-3.0.html.
gui/datasource.cpp:8:** $QT_BEGIN_LICENSE:GPL$
gui/datasource.cpp:21:** the Free Software Foundation and appearing in the file LICENSE.GPL3
gui/datasource.cpp:24:** be met: https://www.gnu.org/licenses/gpl-3.0.html.
gui/datasource.h:8:** $QT_BEGIN_LICENSE:GPL$
gui/datasource.h:21:** the Free Software Foundation and appearing in the file LICENSE.GPL3
gui/datasource.h:24:** be met: https://www.gnu.org/licenses/gpl-3.0.html.
```

**Comment by jlebar** [comment]
Heh, it's just spelled differently.

❯ git grep -li 'GNU General Public License' | cat
LICENSE
common/include/packet_types.h
common/libs/checksum/checksum.cpp
common/libs/checksum/checksum.h
controller/COPYING
controller/include/alarm.h
controller/include/blower.h
controller/include/comms.h
controller/include/eeprom.h
controller/include/errors.h
controller/include/parameters.h
controller/include/pid.h
controller/include/sensors.h
controller/include/serialIO.h
controller/include/types.h
controller/include/ventilator.h
controller/include/version.h
controller/include/watchdog.h
controller/src/FixMoreLungs.cpp
controller/src/alarm.cpp
controller/src/blower.cpp
controller/src/comms.cpp
controller/src/eeprom.cpp
controller/src/parameters.cpp
controller/src/pid.cpp
controller/src/sensors.cpp
controller/src/serialIO.cpp
controller/src/ventilator.cpp
controller/src/version.cpp
controller/src/watchdog.cpp
gui/ControlPanel.qml
gui/ScopeView.qml
gui/datasource.cpp
gui/datasource.h

**Comment by neelfirst** [comment]
I just realized that lol :p I think I can recursive sed this away, just will have to get to it a bit later.

**Comment by jlebar** [comment]
Checked out this branch and ran

```
❯ git grep -l GNU | cat
controller/test/include/ArduinoSim.h
controller/test/include/SensorTests.h
controller/test/src/ArduinoSim.cpp
controller/test/src/SensorTests.cpp
gui/ControlPanel.qml
gui/ScopeView.qml
gui/datasource.cpp
gui/datasource.h
```

Should `controller/test` be updated as well?

**Comment by neelfirst** [comment]
Missed those when I merged master into the branch.

I'm leaving gui/* since they are part of the QT license.

**Pull request merged**
